resources:
- name: scripts 
  type: git
  source:
    uri: https://github.com/18F/concourse-compliance-testing.git
    branch: multi-file
- name: zap-collector-json
  type: s3
  source:
    bucket: {{aws-bucket}} 
    versioned_file: {{aws-zap-json}}
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}

jobs:
- name: zap-scan 
  plan:
  - get: scripts 
  - task: scan-owasp
    file: scripts/task-owasp.yml
    config:
      params:
        LIVE_TARGET: {{live-target}}
        S3_ACCESS_KEY: {{aws-access-key}}
        S3_SECRET_KEY: {{aws-secret-key}}
        S3_BUCKET: {{aws-bucket}}

